// src/app/sections/home/home.component.ts
import { NONE_TYPE } from '@angular/compiler';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  text:string = "";
  tel:number = NaN;

  constructor() { }

  ngOnInit(): void {
  }

  getNumber():string{
    if (isNaN(this.tel)){
      return '';
    }else{
      return this.tel.toString();
    }
  }

  getText():string{
    return this.text.split(' ').join('%20')
  }

  generateLink():string{
    return(
      `https://wa.me/${this.getNumber()}?text=${this.getText()}`
    )
  }

  copyURL():void{
    navigator.clipboard.writeText(this.generateLink().toString());
  }

}

<div class="container">
    <div class="row">

        <div class="col-md-6 p-5 text-center contenedor">
            <h1 style="margin-bottom: 100px;">Genera tu Link personalizado</h1>
            <div class="container-fluid" style="padding: 20px;">
                <div class="row">
                    <div class="col-3">
                        <div class="mb-3">
                            <label for="tel" class="form-label">Area</label>
                            <input
                                id="tel"
                                type="number"
                                class="form-control"
                                [(ngModel)]="area" />
                        </div>
                    </div>
                    <div class="col-9">
                        <div class="mb-3">
                            <label for="tel" class="form-label">Número de Teléfono</label>
                            <input
                                id="tel"
                                type="number"
                                class="form-control"
                                [(ngModel)]="tel" />
                        </div>  
                    </div>
                </div>
            </div> 

            <div class="mb-3" style="padding: 20px;">
                <label for="mensaje" class="form-label">Mensaje</label>
                <textarea
                    id="mensaje"
                    class="form-control"
                    [(ngModel)]="text"
                    rows="3">
                </textarea>
            </div>

            <div class="d-grid gap-2" style="padding: 20px;" >
                <button class="btn" (click)="copyURL();" type="button">Copiar Link</button>
            </div>
        </div>

        <div class="col-md-6 p-5">
            <div class="wslg-device">
                <div class="wslg-device-header">
                    <div class="wslg-speaker"></div>
                </div>
                <div class="wslg-device-body">
                    <div class="wslg-screen">
                        <div class="wslg-screen-header">
                            <div class="wpp-pre-head"></div>
                            <div class="wpp-head">
                                <div class="row text-white no-m">
                                    <div class="col-1 text-center">
                                        <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                    </div>
                                    <div class="col-2">
                                        <img src="../../../assets/img/no_profile.png" alt="IMG" class="img-fluid wpp-img" />
                                    </div>
                                    <div class="col-4">
                                        <p class="wpp-name">+&nbsp;{{getArea()}}&nbsp;{{getNumber()}}</p>
                                        <p class="wpp-status">Online</p>
                                    </div>
                                    <div class="col-1">
                                        <i class="fa fa-video-camera" aria-hidden="true"></i>
                                    </div>
                                    <div class="col-1"></div>
                                    <div class="col-1">
                                        <i class="fa fa-phone" aria-hidden="true"></i>
                                    </div>
                                    <div class="col-1"></div>
                                    <div class="col-1 text-center">
                                        <img src="../../../assets/img/elipsis-v.png" alt="IMG" style="height: 17px;margin-top: 17px; margin-left: -12px;" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="wslg-screen-body">
                            <div class="wslg-screen-body-message">
                                <div class="wslg-screen-body-message--bubble">
                                    <div class="wslg-text container-fluid">
                                        <div class="row">
                                            <div class="col-2">
                                                <img
                                                    src="../../../assets/img/wslg-chat-emoji.png"
                                                    class="img-fluid"
                                                    alt="" />
                                            </div>
                                            <div class="col-8">{{ text }}</div>
                                            <div class="col-2">
                                                <img
                                                    src="../../../assets/img/wslg-chat-clip.png"
                                                    style="max-height: 20px;"
                                                    class="img-fluid"
                                                    alt="" />
                                            </div>
                                        </div>
                                        
                                    </div>
                                    <div class="wslg-icons-wrapper" style="max-height: 20px;">
                                        
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="wslg-screen-body-send">
                                <img
                                    src="../../../assets/img/wslg-chat-send.png"
                                    alt="" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="wslg-device-footer">
                    <div class="wslg-button"></div>
                </div>
            </div>
        </div>

    </div>
</div>

// src/components/Home.vue
<script setup lang="ts">
import { ref, computed } from 'vue'

// Reactive state
const text = ref<string>('')
const tel = ref<string>('')
const area = ref<string>('')

// Computed properties
const getNumber = computed(() => {
  return tel.value || ''
})

const getArea = computed(() => {
  return area.value || ''
})

const getText = computed(() => {
  return text.value.split(' ').join('%20')
})

const generateLink = computed(() => {
  return `https://wa.me/${getArea.value}${getNumber.value}?text=${getText.value}`
})

// Methods
const copyURL = async () => {
  try {
    await navigator.clipboard.writeText(generateLink.value)
    // Optional: Add a toast notification here
  } catch (err) {
    console.error('Failed to copy:', err)
  }
}
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      <!-- Form Section -->
      <div class="contenedor text-center">
        <h1 class="text-3xl md:text-4xl font-bold text-whatsapp mb-16">
          Genera tu Link personalizado
        </h1>
        
        <div class="px-5 py-4">
          <div class="grid grid-cols-12 gap-4">
            <div class="col-span-3">
              <div class="mb-6">
                <label for="area" class="block text-left text-sm font-medium text-gray-700 mb-2">
                  Área
                </label>
                <input
                  id="area"
                  v-model="area"
                  type="number"
                  placeholder="54"
                  class="w-full px-4 py-2 border-2 border-whatsapp rounded-lg focus:outline-none focus:ring-2 focus:ring-whatsapp focus:border-transparent transition-all"
                />
              </div>
            </div>
            <div class="col-span-9">
              <div class="mb-6">
                <label for="tel" class="block text-left text-sm font-medium text-gray-700 mb-2">
                  Número de Teléfono
                </label>
                <input
                  id="tel"
                  v-model="tel"
                  type="number"
                  placeholder="1123882753"
                  class="w-full px-4 py-2 border-2 border-whatsapp rounded-lg focus:outline-none focus:ring-2 focus:ring-whatsapp focus:border-transparent transition-all"
                />
              </div>
            </div>
          </div>
        </div>

        <div class="px-5 py-4">
          <div class="mb-6">
            <label for="mensaje" class="block text-left text-sm font-medium text-gray-700 mb-2">
              Mensaje
            </label>
            <textarea
              id="mensaje"
              v-model="text"
              rows="3"
              placeholder="Hola, me comunico desde tu web, me gustaría saber los precios de https://vasak.net.ar/"
              class="w-full px-4 py-2 border-2 border-whatsapp rounded-lg focus:outline-none focus:ring-2 focus:ring-whatsapp focus:border-transparent transition-all resize-none"
            ></textarea>
          </div>
        </div>

        <div class="px-5 py-4">
          <p class="text-sm text-gray-500 mb-6">
            Verifique la forma de uso en la parte inferior de la página en caso de no saber qué poner en cada campo. 
            En caso de que no aclare sus dudas comuníquese con <span class="font-bold text-whatsapp">Vasak</span>.
          </p>
        </div>

        <div class="px-5 py-4">
          <button
            @click="copyURL"
            type="button"
            class="w-full bg-whatsapp hover:bg-whatsapp-dark text-white font-semibold py-3 px-6 rounded-lg transition-colors duration-200 shadow-md hover:shadow-lg transform hover:-translate-y-0.5"
          >
            Copiar Link
          </button>
        </div>
      </div>

      <!-- Device Preview Section -->
      <div class="flex items-center justify-center p-5">
        <div class="wslg-device">
          <div class="wslg-device-header">
            <div class="wslg-speaker"></div>
          </div>
          <div class="wslg-device-body">
            <div class="wslg-screen">
              <div class="wslg-screen-header">
                <div class="wpp-pre-head"></div>
                <div class="wpp-head">
                  <div class="grid grid-cols-12 text-white no-m items-center px-2">
                    <div class="col-span-1 text-center">
                      <font-awesome-icon :icon="['fas', 'arrow-left']" class="text-white text-lg" />
                    </div>
                    <div class="col-span-2">
                      <img 
                        src="/assets/img/no_profile.png" 
                        alt="Profile" 
                        class="wpp-img w-8 h-8"
                      />
                    </div>
                    <div class="col-span-4">
                      <p class="wpp-name">+ {{ getArea }} {{ getNumber }}</p>
                      <p class="wpp-status">Online</p>
                    </div>
                    <div class="col-span-1 text-center">
                      <font-awesome-icon :icon="['fas', 'video']" class="text-white text-lg" />
                    </div>
                    <div class="col-span-1"></div>
                    <div class="col-span-1 text-center">
                      <font-awesome-icon :icon="['fas', 'phone']" class="text-white text-lg" />
                    </div>
                    <div class="col-span-1"></div>
                    <div class="col-span-1 text-center">
                      <img 
                        src="/assets/img/elipsis-v.png" 
                        alt="Menu" 
                        class="h-4 inline-block"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div class="wslg-screen-body">
                <div class="wslg-screen-body-message">
                  <div class="wslg-screen-body-message--bubble">
                    <div class="wslg-text px-4">
                      <div class="grid grid-cols-12 gap-2 items-center">
                        <div class="col-span-2">
                          <img 
                            src="/assets/img/wslg-chat-emoji.png" 
                            class="w-full"
                            alt="Emoji"
                          />
                        </div>
                        <div class="col-span-8 text-sm">{{ text }}</div>
                        <div class="col-span-2">
                          <img 
                            src="/assets/img/wslg-chat-clip.png" 
                            class="max-h-5 w-full"
                            alt="Clip"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="wslg-screen-body-send">
                  <img 
                    src="/assets/img/wslg-chat-send.png" 
                    alt="Send" 
                    class="h-8"
                  />
                </div>
              </div>
            </div>
          </div>
          <div class="wslg-device-footer">
            <div class="wslg-button"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* Component-specific styles if needed */
</style>
